### ISSUE TITLE
Runtime Error: SimpleITK Cannot Read Series - Expecting DICOM Input?

### ISSUE THREAD

**Issue by Negar-Shah** [UMEssen/Body-and-Organ-Analysis#34]
I am encountering an error while attempting to run a model using Docker and command-line tools. Below is the Docker command used:

``` bash
docker run \
    --rm \
    -v $INPUT_FILE:/path/to/nifti_input \
    -v $WORKING_DIR:/path/to/output_folder \
    -v $LOCAL_WEIGHTS_PATH:/app/weights \ 
    --runtime=nvidia \
    --network host \
    --shm-size=8g --ulimit memlock=-1 --ulimit stack=67108864 \
    --entrypoint /bin/sh \
    shipai/boa-cli \
    -c \
    "python body_organ_analysis --input-image /image.nii.gz --output-dir /workspace/ --models all --verbose"
```

Issue
Upon running the command, I receive the following traceback error indicating an issue with the input file:

``` bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/body_organ_analysis/__main__.py", line 4, in <module>
    run()
  File "/usr/local/lib/python3.8/dist-packages/body_organ_analysis/cli.py", line 168, in run
    analyze_ct(
  File "/usr/local/lib/python3.8/dist-packages/body_organ_analysis/commands.py", line 54, in analyze_ct
    ct_path, ct_info = get_image_info(
  File "/usr/local/lib/python3.8/dist-packages/body_organ_analysis/compute/io.py", line 245, in get_image_info
    image, dicom_files = _load_series_from_disk(input_folder)
  File "/usr/local/lib/python3.8/dist-packages/body_organ_analysis/compute/io.py", line 195, in _load_series_from_disk
    image = reader.Execute()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/SimpleITK/SimpleITK.py", line 8276, in Execute
    return _SimpleITK.ImageSeriesReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageSeriesReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageSeriesReader.cxx:129:
sitk::ERROR: File names information is empty. Cannot read series.
```

Questions
1- It seems like the input must be in DICOM format, correct?
2- What exactly should $INPUT_FILE be referring to in terms of file type and contents?

Thank you in advance,
Negar

**Comment by JannisStraus** [comment]
Hi,

Thanks for opening the issue. The $INPUT_FILE can be in DICOM format or in NIfTI format (.nii.gz). $INPUT_FILE should be the path to the directory where the image is stored. If it is a DICOM series it will be converted to a NIfTI automatically.

It seems that the error occurs because the paths aren't set correct. You should set the `INPUT_FILE` and `WORKING_DIR` variables beforehand or hardcode them with `/path/to/nifti_input` and `/path/to/output_folder`. The `/path/to/nifti_input` now should be replaced with `/image.nii.gz` and `/path/to/output_folder` should be replaced with `/workspace`. `/image.nii.gz` and  `/workspace` shouldn't be changed because they are the specific path used in the virtual docker image. I hope that this solves your problem. If not fell free to reply.

Best regards
Jannis

**Comment by Negar-Shah** [comment]
Thank you! It works now! I changed the INPUT_FILE and WORKING_DIR as you mentioned. Still, I got the error for nifti inputs, but it works for DICOM series.
Thanks the team for great works!
